import { ComponentRegistry } from "../types/ComponentRegistry";
import { ViewComponent } from "../types/ViewComponent";

const registry = ComponentRegistry.getInstance();

const componentConfigs: Array<{ id: string; config: any }> = [
    // Stock
    {
        id: "time-series-chart",
        config: {
            label: "Time Series Chart",
            description: "Displays stock price history as a time series chart",
            tags: ["chart", "stock", "time series", "price", "graph"],
            height: 300,
            width: 700,
            isContainer: false,
            resizable: true,
            maintainAspectRatio: true,
            widthRatio: 16,
            heightRatio: 9,
            heightWidthRatioMultiplier: 0,
            visible: true,
            enabled: true,
            minimumProficiencyRequirements: {},
            requiresInternet: true,
        },
    },
    {
        id: "ticker-search-bar",
        config: {
            label: "Ticker Search Bar",
            description: "Search bar for finding and selecting stock tickers",
            tags: ["search", "ticker", "stock", "search bar"],
            height: 50,
            width: 400,
            isContainer: false,
            resizable: true,
            maintainAspectRatio: false,
            widthRatio: 1,
            heightRatio: 1,
            heightWidthRatioMultiplier: 0,
            visible: true,
            enabled: true,
            minimumProficiencyRequirements: {},
            requiresInternet: true,
        },
    },
    {
        id: "ticker-side-panel",
        config: {
            label: "Ticker Side Panel",
            description: "Side panel displaying financial metrics for the selected ticker",
            tags: ["panel", "ticker", "stock", "side panel", "metrics", "financial"],
            height: 600,
            width: 300,
            isContainer: false,
            resizable: true,
            maintainAspectRatio: false,
            widthRatio: 1,
            heightRatio: 2,
            heightWidthRatioMultiplier: 0,
            visible: true,
            enabled: true,
            minimumProficiencyRequirements: {},
            requiresInternet: true,
        },
    },

    // Dashboard
    {
        id: "economic-chart",
        config: {
            label: "Economic Chart",
            description: "Displays macroeconomic data as a chart",
            tags: ["chart", "economic", "macro", "graph", "economy"],
            height: 300,
            width: 700,
            isContainer: false,
            resizable: true,
            maintainAspectRatio: true,
            widthRatio: 16,
            heightRatio: 9,
            heightWidthRatioMultiplier: 0,
            visible: true,
            enabled: true,
            minimumProficiencyRequirements: {},
            requiresInternet: true,
        },
    },

    // Learning Module
    {
        id: "slide",
        config: {
            label: "Slide",
            description: "Individual slide in a slideshow presentation",
            tags: ["slide", "presentation", "slideshow", "learning"],
            height: 450,
            width: 800,
            isContainer: false,
            resizable: true,
            maintainAspectRatio: true,
            widthRatio: 16,
            heightRatio: 9,
            heightWidthRatioMultiplier: 0,
            visible: true,
            enabled: true,
            minimumProficiencyRequirements: {},
            requiresInternet: false,
        },
    },
    {
        id: "slideshow-window",
        config: {
            label: "Slideshow Window",
            description: "Window for displaying slideshow presentations",
            tags: ["slideshow", "presentation", "window", "learning"],
            height: 450,
            width: 800,
            isContainer: false,
            resizable: true,
            maintainAspectRatio: true,
            widthRatio: 16,
            heightRatio: 9,
            heightWidthRatioMultiplier: 0,
            visible: true,
            enabled: true,
            minimumProficiencyRequirements: {},
            requiresInternet: false,
        },
    },
    {
        id: "learning-module-details",
        config: {
            label: "Learning Module Details",
            description: "Displays details and information about a learning module",
            tags: ["learning", "module", "details", "education"],
            height: 400,
            width: 600,
            isContainer: false,
            resizable: true,
            maintainAspectRatio: false,
            widthRatio: 3,
            heightRatio: 2,
            heightWidthRatioMultiplier: 0,
            visible: true,
            enabled: true,
            minimumProficiencyRequirements: {},
            requiresInternet: false,
        },
    },
    {
        id: "learning-module-page",
        config: {
            label: "Learning Module Page",
            description: "Full page view for a learning module",
            tags: ["learning", "module", "page", "education"],
            height: 600,
            width: 800,
            isContainer: true,
            resizable: true,
            maintainAspectRatio: false,
            widthRatio: 4,
            heightRatio: 3,
            heightWidthRatioMultiplier: 0,
            visible: true,
            enabled: true,
            minimumProficiencyRequirements: {},
            requiresInternet: false,
        },
    },
    {
        id: "powerpoint",
        config: {
            label: "PowerPoint Learning Module",
            description: "Component for displaying PowerPoint presentations",
            tags: ["PowerPoint", "Presentation", "Slideshow", "Learning Module"],
            height: null,
            width: null,
            isContainer: false,
            resizable: true,
            maintainAspectRatio: true,
            widthRatio: 16,
            heightRatio: 9,
            heightWidthRatioMultiplier: 0,
            visible: true,
            enabled: true,
            minimumProficiencyRequirements: {},
            requiresInternet: true,
        },
    },

    // News
    {
        id: "news-listing-summary",
        config: {
            label: "News Listing Summary",
            description: "Summary view of a news article in a listing",
            tags: ["news", "summary", "listing", "article"],
            height: 120,
            width: 600,
            isContainer: false,
            resizable: true,
            maintainAspectRatio: false,
            widthRatio: 5,
            heightRatio: 1,
            heightWidthRatioMultiplier: 0,
            visible: true,
            enabled: true,
            minimumProficiencyRequirements: {},
            requiresInternet: true,
        },
    },
    {
        id: "news-search-bar",
        config: {
            label: "News Search Bar",
            description: "Search bar for finding news articles",
            tags: ["news", "search", "search bar"],
            height: 50,
            width: 400,
            isContainer: false,
            resizable: true,
            maintainAspectRatio: false,
            widthRatio: 1,
            heightRatio: 1,
            heightWidthRatioMultiplier: 0,
            visible: true,
            enabled: true,
            minimumProficiencyRequirements: {},
            requiresInternet: true,
        },
    },
    {
        id: "news-browser",
        config: {
            label: "News Browser",
            description: "Browser for viewing and navigating news articles",
            tags: ["news", "browser", "articles"],
            height: 600,
            width: 800,
            isContainer: false,
            resizable: true,
            maintainAspectRatio: false,
            widthRatio: 4,
            heightRatio: 3,
            heightWidthRatioMultiplier: 0,
            visible: true,
            enabled: true,
            minimumProficiencyRequirements: {},
            requiresInternet: true,
        },
    },
    {
        id: "news-listing",
        config: {
            label: "News Listing",
            description: "List view of news articles",
            tags: ["news", "listing", "articles", "list"],
            height: 600,
            width: 400,
            isContainer: false,
            resizable: true,
            maintainAspectRatio: false,
            widthRatio: 2,
            heightRatio: 3,
            heightWidthRatioMultiplier: 0,
            visible: true,
            enabled: true,
            minimumProficiencyRequirements: {},
            requiresInternet: true,
        },
    },

    // Settings
    {
        id: "settings-row",
        config: {
            label: "Settings Row",
            description: "A single row in the settings panel",
            tags: ["settings", "row", "configuration"],
            height: 48,
            width: 600,
            isContainer: false,
            resizable: true,
            maintainAspectRatio: false,
            widthRatio: 1,
            heightRatio: 1,
            heightWidthRatioMultiplier: 0,
            visible: true,
            enabled: true,
            minimumProficiencyRequirements: {},
            requiresInternet: false,
        },
    },
    {
        id: "settings-row-label",
        config: {
            label: "Settings Row Label",
            description: "Label element for a settings row",
            tags: ["settings", "label", "configuration"],
            height: 48,
            width: 200,
            isContainer: false,
            resizable: true,
            maintainAspectRatio: false,
            widthRatio: 1,
            heightRatio: 1,
            heightWidthRatioMultiplier: 0,
            visible: true,
            enabled: true,
            minimumProficiencyRequirements: {},
            requiresInternet: false,
        },
    },
    {
        id: "settings-row-value",
        config: {
            label: "Settings Row Value",
            description: "Value element for a settings row",
            tags: ["settings", "value", "configuration"],
            height: 48,
            width: 400,
            isContainer: false,
            resizable: true,
            maintainAspectRatio: false,
            widthRatio: 1,
            heightRatio: 1,
            heightWidthRatioMultiplier: 0,
            visible: true,
            enabled: true,
            minimumProficiencyRequirements: {},
            requiresInternet: false,
        },
    },

    // Shared
    {
        id: "symbol-search-bar",
        config: {
            label: "Symbol Search Bar",
            description: "Shared search bar for finding financial symbols",
            tags: ["search", "symbol", "ticker", "shared", "search bar"],
            height: 50,
            width: 400,
            isContainer: false,
            resizable: true,
            maintainAspectRatio: false,
            widthRatio: 1,
            heightRatio: 1,
            heightWidthRatioMultiplier: 0,
            visible: true,
            enabled: true,
            minimumProficiencyRequirements: {},
            requiresInternet: true,
        },
    },

    // Top-level views
    {
        id: "about",
        config: {
            label: "About",
            description: "About page for the application",
            tags: ["about", "info", "information"],
            height: 600, width: 800, isContainer: false, resizable: true,
            maintainAspectRatio: false, widthRatio: 4, heightRatio: 3,
            heightWidthRatioMultiplier: 0, visible: true, enabled: true,
            minimumProficiencyRequirements: {}, requiresInternet: false,
        },
    },
    {
        id: "analysis",
        config: {
            label: "Analysis",
            description: "Stock and financial analysis view",
            tags: ["analysis", "stock", "financial", "research"],
            height: 600, width: 1000, isContainer: false, resizable: true,
            maintainAspectRatio: false, widthRatio: 5, heightRatio: 3,
            heightWidthRatioMultiplier: 0, visible: true, enabled: true,
            minimumProficiencyRequirements: {}, requiresInternet: true,
        },
    },
    {
        id: "buy-report",
        config: {
            label: "Buy Report",
            description: "Report view for buy recommendations",
            tags: ["buy", "report", "recommendation", "stock"],
            height: 600, width: 800, isContainer: false, resizable: true,
            maintainAspectRatio: false, widthRatio: 4, heightRatio: 3,
            heightWidthRatioMultiplier: 0, visible: true, enabled: true,
            minimumProficiencyRequirements: {}, requiresInternet: true,
        },
    },
    {
        id: "chatbot",
        config: {
            label: "Chatbot",
            description: "AI chatbot for financial questions and commands",
            tags: ["chatbot", "ai", "assistant", "chat"],
            height: 500, width: 400, isContainer: false, resizable: true,
            maintainAspectRatio: false, widthRatio: 2, heightRatio: 5,
            heightWidthRatioMultiplier: 0, visible: true, enabled: true,
            minimumProficiencyRequirements: {}, requiresInternet: true,
        },
    },
    {
        id: "forecast",
        config: {
            label: "Forecast",
            description: "Stock price forecast view",
            tags: ["forecast", "prediction", "stock", "price"],
            height: 600, width: 800, isContainer: false, resizable: true,
            maintainAspectRatio: false, widthRatio: 4, heightRatio: 3,
            heightWidthRatioMultiplier: 0, visible: true, enabled: true,
            minimumProficiencyRequirements: {}, requiresInternet: true,
        },
    },
    {
        id: "forecast-feature",
        config: {
            label: "Forecast Feature",
            description: "Individual feature input for the forecast model",
            tags: ["forecast", "feature", "input", "model"],
            height: 80, width: 400, isContainer: false, resizable: true,
            maintainAspectRatio: false, widthRatio: 5, heightRatio: 1,
            heightWidthRatioMultiplier: 0, visible: true, enabled: true,
            minimumProficiencyRequirements: {}, requiresInternet: false,
        },
    },
    {
        id: "forecast-model",
        config: {
            label: "Forecast Model",
            description: "Configuration and display of the forecast model",
            tags: ["forecast", "model", "machine learning", "prediction"],
            height: 600, width: 800, isContainer: false, resizable: true,
            maintainAspectRatio: false, widthRatio: 4, heightRatio: 3,
            heightWidthRatioMultiplier: 0, visible: true, enabled: true,
            minimumProficiencyRequirements: {}, requiresInternet: true,
        },
    },
    {
        id: "home",
        config: {
            label: "Home",
            description: "Application home page and dashboard",
            tags: ["home", "dashboard", "overview"],
            height: 600, width: 1000, isContainer: true, resizable: true,
            maintainAspectRatio: false, widthRatio: 5, heightRatio: 3,
            heightWidthRatioMultiplier: 0, visible: true, enabled: true,
            minimumProficiencyRequirements: {}, requiresInternet: true,
        },
    },
    {
        id: "investment-pool",
        config: {
            label: "Investment Pool",
            description: "View for managing investment pools",
            tags: ["investment", "pool", "portfolio", "management"],
            height: 600, width: 800, isContainer: false, resizable: true,
            maintainAspectRatio: false, widthRatio: 4, heightRatio: 3,
            heightWidthRatioMultiplier: 0, visible: true, enabled: true,
            minimumProficiencyRequirements: {}, requiresInternet: true,
        },
    },
    {
        id: "learn",
        config: {
            label: "Learn",
            description: "Learning hub for financial education modules",
            tags: ["learn", "education", "modules", "courses"],
            height: 600, width: 1000, isContainer: true, resizable: true,
            maintainAspectRatio: false, widthRatio: 5, heightRatio: 3,
            heightWidthRatioMultiplier: 0, visible: true, enabled: true,
            minimumProficiencyRequirements: {}, requiresInternet: false,
        },
    },
    {
        id: "moving-avg-chart",
        config: {
            label: "Moving Average Chart",
            description: "Chart displaying moving average indicators for a stock",
            tags: ["chart", "moving average", "indicator", "stock", "technical analysis"],
            height: 300, width: 700, isContainer: false, resizable: true,
            maintainAspectRatio: true, widthRatio: 16, heightRatio: 9,
            heightWidthRatioMultiplier: 0, visible: true, enabled: true,
            minimumProficiencyRequirements: {}, requiresInternet: true,
        },
    },
    {
        id: "news",
        config: {
            label: "News",
            description: "Financial news page",
            tags: ["news", "articles", "financial news"],
            height: 600, width: 800, isContainer: true, resizable: true,
            maintainAspectRatio: false, widthRatio: 4, heightRatio: 3,
            heightWidthRatioMultiplier: 0, visible: true, enabled: true,
            minimumProficiencyRequirements: {}, requiresInternet: true,
        },
    },
    {
        id: "portfolio",
        config: {
            label: "Portfolio",
            description: "Portfolio management and overview page",
            tags: ["portfolio", "investments", "holdings", "management"],
            height: 600, width: 1000, isContainer: true, resizable: true,
            maintainAspectRatio: false, widthRatio: 5, heightRatio: 3,
            heightWidthRatioMultiplier: 0, visible: true, enabled: true,
            minimumProficiencyRequirements: {}, requiresInternet: true,
        },
    },
    {
        id: "risk-analysis",
        config: {
            label: "Risk Analysis",
            description: "Risk analysis view for evaluating investment risk",
            tags: ["risk", "analysis", "investment", "assessment"],
            height: 600, width: 1000, isContainer: false, resizable: true,
            maintainAspectRatio: false, widthRatio: 5, heightRatio: 3,
            heightWidthRatioMultiplier: 0, visible: true, enabled: true,
            minimumProficiencyRequirements: {}, requiresInternet: true,
        },
    },
    {
        id: "risk-survey",
        config: {
            label: "Risk Survey",
            description: "Survey for assessing user risk tolerance",
            tags: ["risk", "survey", "questionnaire", "tolerance"],
            height: 600, width: 700, isContainer: false, resizable: true,
            maintainAspectRatio: false, widthRatio: 4, heightRatio: 3,
            heightWidthRatioMultiplier: 0, visible: true, enabled: true,
            minimumProficiencyRequirements: {}, requiresInternet: false,
        },
    },
    {
        id: "roc-chart",
        config: {
            label: "ROC Chart",
            description: "Rate of Change chart for technical stock analysis",
            tags: ["chart", "ROC", "rate of change", "indicator", "technical analysis"],
            height: 300, width: 700, isContainer: false, resizable: true,
            maintainAspectRatio: true, widthRatio: 16, heightRatio: 9,
            heightWidthRatioMultiplier: 0, visible: true, enabled: true,
            minimumProficiencyRequirements: {}, requiresInternet: true,
        },
    },
    {
        id: "rsi-chart",
        config: {
            label: "RSI Chart",
            description: "Relative Strength Index chart for technical stock analysis",
            tags: ["chart", "RSI", "relative strength index", "indicator", "technical analysis"],
            height: 300, width: 700, isContainer: false, resizable: true,
            maintainAspectRatio: true, widthRatio: 16, heightRatio: 9,
            heightWidthRatioMultiplier: 0, visible: true, enabled: true,
            minimumProficiencyRequirements: {}, requiresInternet: true,
        },
    },
    {
        id: "settings",
        config: {
            label: "Settings",
            description: "Application settings and configuration page",
            tags: ["settings", "configuration", "preferences", "options"],
            height: 600, width: 700, isContainer: true, resizable: true,
            maintainAspectRatio: false, widthRatio: 4, heightRatio: 3,
            heightWidthRatioMultiplier: 0, visible: true, enabled: true,
            minimumProficiencyRequirements: {}, requiresInternet: false,
        },
    },
    {
        id: "time-series",
        config: {
            label: "Time Series",
            description: "Full stock time series view with charts and data",
            tags: ["stock", "time series", "chart", "price history"],
            height: 600, width: 1000, isContainer: true, resizable: true,
            maintainAspectRatio: false, widthRatio: 5, heightRatio: 3,
            heightWidthRatioMultiplier: 0, visible: true, enabled: true,
            minimumProficiencyRequirements: {}, requiresInternet: true,
        },
    },
    {
        id: "stock-analysis",
        config: {
            label: "Stock Analysis",
            description: "Detailed stock analysis page with multiple indicators",
            tags: ["stock", "analysis", "indicators", "technical analysis"],
            height: 600, width: 1000, isContainer: true, resizable: true,
            maintainAspectRatio: false, widthRatio: 5, heightRatio: 3,
            heightWidthRatioMultiplier: 0, visible: true, enabled: true,
            minimumProficiencyRequirements: {}, requiresInternet: true,
        },
    },
    {
        id: "stock-analysis-search-bar",
        config: {
            label: "Stock Analysis Search Bar",
            description: "Search bar for the stock analysis page",
            tags: ["search", "stock", "analysis", "search bar"],
            height: 50, width: 400, isContainer: false, resizable: true,
            maintainAspectRatio: false, widthRatio: 1, heightRatio: 1,
            heightWidthRatioMultiplier: 0, visible: true, enabled: true,
            minimumProficiencyRequirements: {}, requiresInternet: true,
        },
    },

    // Portfolio
    {
        id: "portfolio-creation",
        config: {
            label: "Portfolio Creation",
            description: "Interface for creating and managing investment portfolios",
            tags: ["portfolio", "creation", "investment", "management"],
            height: 600,
            width: 800,
            isContainer: false,
            resizable: true,
            maintainAspectRatio: false,
            widthRatio: 4,
            heightRatio: 3,
            heightWidthRatioMultiplier: 0,
            visible: true,
            enabled: true,
            minimumProficiencyRequirements: {},
            requiresInternet: true,
        },
    },
];

export function registerAllComponents(): void {
    for (const { id, config } of componentConfigs) {
        if (!registry.getById(id)) {
            registry.register(id, new ViewComponent(config));
        }
    }
}
