# Generated by Django 5.1.3 on 2025-03-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_be', '0009_scrapeddatameta_content_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('dataset', models.CharField(max_length=255)),
                ('ROUGE1', models.FloatField()),
                ('ROUGE2', models.FloatField()),
                ('ROUGE_L', models.FloatField()),
                ('ROUGE_LSum', models.FloatField()),
                ('BERTScoreF1', models.FloatField()),
                ('BERTScorePrecision', models.FloatField()),
                ('BERTScoreRecall', models.FloatField()),
            ],
        ),
    ]
