# Generated by Django 5.2.7 on 2025-10-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_be', '0010_scrapeddata_title_scrapeddatameta_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document_y',
        ),
    ]
