# Generated by Django 5.1.3 on 2025-03-20 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_be', '0010_scrapeddata_title_scrapeddatameta_title'),
        ('chatbot_be', '0011_modelstats_created_at'),
    ]

    operations = [
    ]
