# Generated by Django 5.1.3 on 2025-03-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_be', '0012_merge_20250320_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelstats',
            name='STSScore',
            field=models.FloatField(default=0.0),
        ),
    ]
