# Generated by Django 4.2.18 on 2025-02-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_be', '0009_scrapeddatameta_content_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='title',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapeddatameta',
            name='title',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
    ]
